files:
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config/pic32mk_mcm_curiosity_pro/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: B7A28744C87EF16433C5CDD9C8AD4859
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B7A28744C87EF16433C5CDD9C8AD4859
- generatedChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 9F977ADA60E725E676D02F044CF4F035
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9F977ADA60E725E676D02F044CF4F035
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: 7B29B2019511C46F2432BA7318521156
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7B29B2019511C46F2432BA7318521156
- generatedChecksum: 171F05807BE1DA35533DFD415B32C57E
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart6.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 171F05807BE1DA35533DFD415B32C57E
- generatedChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
- generatedChecksum: AEAD678D52A900BF13F45EFDA811BC10
  logicalPath: config/pic32mk_mcm_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEAD678D52A900BF13F45EFDA811BC10
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 60CCF2FCB84A0FA9AA8C1607725D47A4
  logicalPath: config/pic32mk_mcm_curiosity_pro/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 60CCF2FCB84A0FA9AA8C1607725D47A4
- generatedChecksum: 76016C9804D6DE17B74C92D82294562E
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 76016C9804D6DE17B74C92D82294562E
- generatedChecksum: 9E7BBC6F6BBB3C770EFC72EE2BE887B3
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E7BBC6F6BBB3C770EFC72EE2BE887B3
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 848286252841AFE9AEEC10E0CD784605
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 848286252841AFE9AEEC10E0CD784605
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
- generatedChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart6.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
